openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/project-narwhal/project-narwhal/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Universal QR Code API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: collection
    description: Information and updating of collections
  - name: item
    description: Information and updating of individual items
paths:
  /collection/{id}:
    get:
      tags:
        - collection
      summary: get info about a collection
      operationId: getCollectionById
      description: returns details for a collection
      parameters:
        - in: path
          name: id
          description: id of record to look up
          required: true
          schema:
            type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Collection"
        "400":
          description: bad input parameter
    post:
      tags:
        - collection
      summary: adds a new collection
      operationId: addCollection
      description: Adds a new collection
      responses:
        "201":
          description: collection created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing collection already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Collection"
        description: Inventory item to add
components:
  schemas:
    Collection:
      type: object
      required:
        - id
        - items
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"

        releaseDate:
          type: string
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
    Item:
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 7fa7ea76-0d7e-4e6c-8bb0-abb89e38d6c9
        name:
          type: string
          example: Kush OG
      type: object
