openapi: 3.0.0
info:
  description: Sample API for Universal QR Codes
  version: "1.0.0"
  title: Universal QR Code API
  contact:
    email: engineering@nabis.com
tags:
  - name: collection
    description: Information and updating of collections
  - name: skubatch
    description: Information and updating skubatches
  - name: sku
    description: Information about sku details
paths:
  /collection/{id}:
    get:
      tags:
        - collection
      summary: get info about a collection
      operationId: getCollectionById
      description: returns details for a collection
      parameters:
        - in: path
          name: id
          description: id of record to look up
          required: true
          schema:
            type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                item:
                  $ref: "#/components/schemas/Collection"
        "400":
          description: bad input parameter
  /collection/:
    post:
      tags:
        - collection
      summary: adds a new collection
      operationId: addCollection
      description: Adds a new collection
      responses:
        "201":
          description: collection created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"
        "400":
          description: "invalid input, object invalid"
        "409":
          description: "an existing collection already exists"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CollectionInput"
        description: Collection to create
  /collection/search:
    get:
      tags:
        - collection
      parameters:
        - in: query
          name: identifier
          schema:
            type: string
          description: Search by the identifier of a collection
        - in: query
          name: collectionType
          schema:
            $ref: "#/components/schemas/CollectionType"
      responses:
        "200":
          description: "Collections that match the search"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Collection"

  /skubatch/{id}:
    get:
      tags:
        - skubatch
      parameters:
        - in: path
          name: id
          description: id of record to look up
          required: true
          schema:
            type: string
      responses:
        "200":
          description: skubatch matching input id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SkuBatch"
    put:
      tags:
        - skubatch
      parameters:
        - in: path
          name: id
          description: id of record to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SkuBatch"
      responses:
        "200":
          description: updated skubatch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SkuBatch"
components:
  schemas:
    CollectionType:
      type: string
      enum: ["batch", "case", "regulator"]
      description: The type of collection, can be batch, case or regulator
    UuidArray:
      type: array
      items:
        type: string
        format: uuid
    CollectionNoSkuBatchesArray:
      type: object
      required:
        - identifier
        - skubatches
        - name
      properties:
        id:
          type: string
          format: uuid
        identifier:
          type: string
          description: Metrc Id / Batch Id / Case Id
        name:
          type: string
          description: Name for your collection
        createdDate:
          type: string
          format: date-time
        collectionType:
          $ref: "#/components/schemas/CollectionType"
    CollectionInput:
      type: object
      allOf:
        - $ref: "#/components/schemas/CollectionNoSkuBatchesArray"
      properties:
        skubatches:
          type: array
          items:
            $ref: "#/components/schemas/UuidArray"
    Collection:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdDate:
          type: string
          format: date-time
      allOf:
        - $ref: "#/components/schemas/CollectionInput"

    SkuBatchInput:
      required:
        - name
      properties:
        skuId:
          type: string
          format: uuid
        thcPercent:
          type: number
          format: float
        cbdPercent:
          type: number
          format: float
        otherPercent:
          type: number
          format: float
        batchCollection:
          type: array
          description: Collection of skubatches that make up the batch that this skubatch is a part of
          items:
            $ref: "#/components/schemas/CollectionNoSkuBatchesArray"
        regulatorCollection:
          type: array
          description: Collection of skubatches that make up the metrc tags / regulator IDs that this skubatch is a part of
          items:
            $ref: "#/components/schemas/CollectionNoSkuBatchesArray"
        caseCollection:
          type: array
          description: Collection of cases that this skubatch is a part of
          items:
            $ref: "#/components/schemas/CollectionNoSkuBatchesArray"
      type: object
    SkuBatch:
      required:
        - name
        - id
      allOf:
        - $ref: "#/components/schemas/SkuBatchInput"
      properties:
        id:
          type: string
          format: uuid
        createdDate:
          type: string
          format: date-time
      type: object
    Sku:
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Kush OG
        strain:
          type: string
      type: object
